import type { Vehicle } from "@/lib/types";

export const vehicles: Vehicle[] = [
  {
    id: "toyota-corolla-2022",
    brand: "Toyota",
    model: "Corolla",
    year: 2022,
    price: 145000,
    mileageKm: 32000,
    transmission: "Automático",
    fuelType: "Gasolina",
    status: "Disponible",
    isNew: true,
    isVerified: true,
    description: "Sedán confiable, único dueño, mantenimientos al día en agencia.",
    bodyType: "Sedán",
    seats: 5,
    engineDisplacementLiters: 2.0,
    fuelConsumptionKmPerGalon: 38,
    idealFor: "Trayectos diarios en ciudad: bajo consumo y mantenimiento accesible.",
    images: [],
  },
  {
    id: "honda-crv-2021",
    brand: "Honda",
    model: "CR-V",
    year: 2021,
    price: 198000,
    mileageKm: 45000,
    transmission: "Automático",
    fuelType: "Gasolina",
    status: "Disponible",
    isNew: false,
    isVerified: true,
    description: "SUV familiar, espacio amplio, excelente para ciudad y carretera.",
    bodyType: "SUV",
    seats: 5,
    engineDisplacementLiters: 1.5,
    fuelConsumptionKmPerGalon: 30,
    idealFor: "Familias que necesitan espacio y versatilidad para viajes.",
    images: [],
  },
  {
    id: "kia-rio-2020",
    brand: "Kia",
    model: "Rio",
    year: 2020,
    price: 89000,
    mileageKm: 61000,
    transmission: "Manual",
    fuelType: "Gasolina",
    status: "Disponible",
    isNew: false,
    isVerified: false,
    description: "Económico y de bajo consumo, ideal para primer vehículo.",
    bodyType: "Hatchback",
    seats: 5,
    engineDisplacementLiters: 1.4,
    fuelConsumptionKmPerGalon: 40,
    idealFor: "Primer carro: económico, ágil y de mantenimiento sencillo.",
    images: [],
  },
  {
    id: "hyundai-tucson-2023",
    brand: "Hyundai",
    model: "Tucson",
    year: 2023,
    price: 235000,
    mileageKm: 12000,
    transmission: "Automático",
    fuelType: "Híbrido",
    status: "Reservado",
    isNew: true,
    isVerified: true,
    description: "Modelo reciente, motor híbrido, garantía de agencia vigente.",
    bodyType: "SUV",
    seats: 5,
    engineDisplacementLiters: 1.6,
    fuelConsumptionKmPerGalon: 45,
    idealFor: "Eficiencia de combustible sin sacrificar espacio familiar.",
    images: [],
  },
  {
    id: "mazda-3-2019",
    brand: "Mazda",
    model: "3",
    year: 2019,
    price: 102000,
    mileageKm: 73000,
    transmission: "Automático",
    fuelType: "Gasolina",
    status: "Disponible",
    isNew: false,
    isVerified: true,
    description: "Diseño deportivo, interior en buen estado, llantas nuevas.",
    bodyType: "Sedán",
    seats: 5,
    engineDisplacementLiters: 2.0,
    fuelConsumptionKmPerGalon: 36,
    idealFor: "Manejo ágil y diseño, para quien se mueve solo por ciudad.",
    images: [],
  },
  {
    id: "nissan-sentra-2018",
    brand: "Nissan",
    model: "Sentra",
    year: 2018,
    price: 78000,
    mileageKm: 92000,
    transmission: "Automático",
    fuelType: "Gasolina",
    status: "Vendido",
    isNew: false,
    isVerified: false,
    description: "Buen estado general, ideal para uso diario en la ciudad.",
    bodyType: "Sedán",
    seats: 5,
    engineDisplacementLiters: 1.8,
    fuelConsumptionKmPerGalon: 35,
    idealFor: "Uso diario económico dentro de la ciudad.",
    images: [],
  },
  {
    id: "mazda-cx5-2022",
    brand: "Mazda",
    model: "CX-5",
    year: 2022,
    price: 245000,
    mileageKm: 18000,
    transmission: "Automático",
    fuelType: "Gasolina",
    status: "Disponible",
    isNew: true,
    isVerified: true,
    description: "SUV mediana, interior premium, cámara 360 y techo panorámico.",
    bodyType: "SUV",
    seats: 5,
    engineDisplacementLiters: 2.5,
    fuelConsumptionKmPerGalon: 28,
    idealFor: "Viajes frecuentes y familias que necesitan más espacio de carga.",
    images: [],
  },
  {
    id: "bmw-x3-2021",
    brand: "BMW",
    model: "X3",
    year: 2021,
    price: 385000,
    mileageKm: 28000,
    transmission: "Automático",
    fuelType: "Gasolina",
    status: "Disponible",
    isNew: false,
    isVerified: true,
    description: "SUV premium, tracción integral, interior en piel y paquete deportivo.",
    bodyType: "SUV",
    seats: 5,
    engineDisplacementLiters: 2.0,
    fuelConsumptionKmPerGalon: 24,
    idealFor: "Quienes buscan lujo, potencia y espacio en un mismo vehículo.",
    images: [],
  },
];
